### ISSUE TITLE
Bot can not send response message

### ISSUE THREAD

**Issue by JBTeams** [OfficeDev/microsoft-teams-app-quickstarts#46]
Hello, I am on Windows 10 and created a Bot app and followed the README.md. It seems my bot can receive the message, but not reply to the user. I see the message come in through ngrok (POST /api/messages             500 Internal Server Error) and I added a console.log
```
...
            TurnContext.removeRecipientMention(context.activity);
            console.log(context.activity.text.trim());
            switch (context.activity.text.trim()) {
...
```

```
Hello

 [onTurnError] unhandled error: Error: Get Token request returned http error: 400 and server response: {"error":"unauthorized_client","error_description":"AADSTS700016: Application with identifier 'cbe51a19-7270-46d7-9fda-c168aa1a1230' was not found in the directory 'botframework.com'. This can happen if the application has not been installed by the administrator of the tenant 
or consented to by any user in the tenant. You may have sent your authentication request to the wrong tenant.\r\nTrace ID: 8bd147e7-aa6c-4abc-b4f9-5aaace8e2500\r\nCorrelation ID: 53143013-90d1-46f6-9aff-c9f161e0123b\r\nTimestamp: 2020-12-02 21:21:36Z","error_codes":[700016],"timestamp":"2020-12-02 21:21:36Z","trace_id":"8bd147e7-aa6c-4abc-b4f9-5aaace8e2500","correlation_id":"53143013-90d1-46f6-9aff-c9f161e0123b","error_uri":"https://login.microsoftonline.com/error?code=700016"}
(node:21244) UnhandledPromiseRejectionWarning: Error: BotFrameworkAdapter.processActivity(): 500 ERROR
 Error: Get Token request returned http error: 400 and server response: {"error":"unauthorized_client","error_description":"AADSTS700016: Application with identifier 'cbe51a19-7270-46d7-9fda-c168aa1a1230' was not found in the directory 'botframework.com'. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in 
the tenant. You may have sent your authentication request to the wrong tenant.\r\nTrace ID: 8bd147e7-aa6c-4abc-b4f9-5aaace8e2500\r\nCorrelation ID: 53143013-90d1-46f6-9aff-c9f161e0123b\r\nTimestamp: 2020-12-02 21:21:36Z","error_codes":[700016],"timestamp":"2020-12-02 21:21:36Z","trace_id":"8bd147e7-aa6c-4abc-b4f9-5aaace123450","correlation_id":"53143013-90d1-46f6-9aff-c9f161e0123b","error_uri":"https://login.microsoftonline.com/error?code=700016"}
    at Logger.createError (C:\work\teams\MyBotApp\My Bot App\node_modules\adal-node\lib\log.js:216:13)
    at Request._callback (C:\work\teams\MyBotApp\My Bot App\node_modules\adal-node\lib\util.js:130:25)130:25)                                                                                        :185:22)
    at Request.self.callback (C:\work\teams\MyBotApp\My Bot App\node_modules\request\request.js:185:22)                                                                                       154:10)
    at Request.emit (events.js:182:13)
    at Request.<anonymous> (C:\work\teams\MyBotApp\My Bot App\node_modules\request\request.js:1est.js:1076:12)154:10)
    at Request.emit (events.js:182:13)
    at IncomingMessage.<anonymous> (C:\work\teams\MyBotApp\My Bot App\node_modules\request\request.js:1076:12)                                                                                er\lib\botFrameworkAdapter.js:687:27)
    at Object.onceWrapper (events.js:273:13)
    at IncomingMessage.emit (events.js:187:15)                                                 ter.js:12:65)
    at endReadableNT (_stream_readable.js:1094:12)
    at BotFrameworkAdapter.<anonymous> (C:\work\teams\MyBotApp\My Bot App\node_modules\botbuilded either by throwing inside of an async function without a catch block, or by rejecting a promise er\lib\botFrameworkAdapter.js:687:27)
    at Generator.throw (<anonymous>)
    at rejected (C:\work\teams\MyBotApp\My Bot App\node_modules\botbuilder\lib\botFrameworkAdapter.js:12:65)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:21244) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 6)
```

any idea why the bot can not respond to my user? I've tried in the debugger, and in teams. Myself and a coworker have the same issue. I've tried at https://dev.botframework.com/bots and get the same error everywhere.

**Comment by karthigb** [comment]
Hello @JBTeams ,

Did you register the Bot API endpoint in App Studio?

![image](https://user-images.githubusercontent.com/2610557/101221715-1f3e1780-363d-11eb-8091-463c7d7ac11a.png)

**Comment by JBTeams** [comment]
@karthigb yes I did

**Comment by karthigb** [comment]
@JBTeams Thank you for the thorough explanation. I'll look into this and get back to you. I'm glad you have a workaround in the meanwhile.

**Comment by karthigb** [comment]
@JBTeams This looks like it might be a Bot Framework service issue. We're investigating with our partners on that team. Thank you again for bringing this to our attention.
